# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('setup_completed', 'اكتمل التجهيز'), ('suspended', 'موقوف')], db_index=True, default='new', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('suspended_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'مبدع',
                'verbose_name_plural': 'المبدعون',
                'db_table': 'creators',
            },
        ),
        migrations.CreateModel(
            name='KycCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('not_required', 'غير مطلوب'), ('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='not_required', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_checks', to='creators.creator')),
            ],
            options={
                'db_table': 'kyc_checks',
            },
        ),
        migrations.CreateModel(
            name='CreatorConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_version', models.CharField(max_length=30)),
                ('accepted_at', models.DateTimeField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('content_hash', models.CharField(help_text='SHA-256 لنص الشروط المعروض', max_length=64)),
                ('language', models.CharField(default='ar', max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='creators.creator')),
            ],
            options={
                'db_table': 'creator_consents',
                'constraints': [models.UniqueConstraint(fields=('creator', 'terms_version'), name='uniq_consent_per_terms_version')],
            },
        ),
        migrations.CreateModel(
            name='CreatorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=128)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=40)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('integrity_verdict', models.CharField(choices=[('trusted', 'موثوق'), ('untrusted', 'غير موثوق'), ('unknown', 'غير معروف')], default='unknown', max_length=20)),
                ('integrity_checked_at', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('permissions_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='creators.creator')),
            ],
            options={
                'db_table': 'creator_devices',
                'constraints': [models.UniqueConstraint(fields=('creator', 'device_id'), name='uniq_device_per_creator')],
            },
        ),
    ]
