# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=4, default=0, help_text='نسبة مئوية، مثال 5.0000 تعني ٥٪', max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], default='EGP', max_length=3)),
                ('min_fee', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'fee_schedules',
                'indexes': [models.Index(fields=['is_active', 'effective_from'], name='fee_schedul_is_acti_da91b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], default='USD', max_length=3)),
                ('quote_currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], default='EGP', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(choices=[('tiktok', 'سعر TikTok'), ('manual', 'إدخال يدوي'), ('bank', 'سعر البنك')], default='manual', max_length=10)),
                ('effective_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'fx_rates',
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='fx_rate_positive'), models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'source', 'effective_at'), name='uniq_fx_rate_point')],
            },
        ),
    ]
