# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('whatsapp_phone', models.CharField(max_length=20, unique=True)),
                ('whatsapp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('paused', 'موقوف مؤقتًا'), ('blocked', 'محظور')], db_index=True, default='active', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'صاحب حساب استلام',
                'verbose_name_plural': 'أصحاب حسابات الاستلام',
                'db_table': 'account_owners',
            },
        ),
        migrations.CreateModel(
            name='ReceivingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ipa', 'عنوان إنستاباي'), ('mobile', 'محفظة هاتف'), ('bank', 'حساب بنكي')], max_length=10)),
                ('identifier', models.CharField(help_text='عنوان إنستاباي أو رقم الحساب', max_length=120)),
                ('display_label', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('beneficiary_name', models.CharField(blank=True, max_length=150)),
                ('daily_limit_egp', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('monthly_limit_egp', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('max_creators', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('full', 'بلغ السعة'), ('paused', 'موقوف')], db_index=True, default='active', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='receiving.accountowner')),
            ],
            options={
                'db_table': 'receiving_accounts',
            },
        ),
        migrations.CreateModel(
            name='CreatorReceivingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField()),
                ('autofilled_at', models.DateTimeField(blank=True, help_text='وقت تعبئة البيانات داخل TikTok', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='وقت أول تحويل ناجح', null=True)),
                ('active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='creators.creator')),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='receiving.receivingaccount')),
            ],
            options={
                'db_table': 'creator_receiving_assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='receivingaccount',
            constraint=models.UniqueConstraint(fields=('type', 'identifier'), name='uniq_receiving_identifier'),
        ),
        migrations.AddConstraint(
            model_name='receivingaccount',
            constraint=models.CheckConstraint(condition=models.Q(('max_creators__gte', 1)), name='receiving_max_creators_positive'),
        ),
        migrations.AddIndex(
            model_name='creatorreceivingassignment',
            index=models.Index(fields=['receiving_account', 'active'], name='creator_rec_receivi_2a99df_idx'),
        ),
        migrations.AddConstraint(
            model_name='creatorreceivingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('creator',), name='uniq_active_assignment_per_creator'),
        ),
    ]
