# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='مفتاح داخلي مثل withdrawal_sent_owner', max_length=60)),
                ('channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('fcm', 'إشعار تطبيق')], default='whatsapp', max_length=10)),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], max_length=2)),
                ('provider_template_name', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(help_text='النص مع متغيرات {code} {amount} {creator}')),
                ('buttons_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'message_templates',
                'constraints': [models.UniqueConstraint(fields=('key', 'channel', 'language'), name='uniq_template_key_lang')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('fcm', 'إشعار تطبيق')], max_length=10)),
                ('to_ref', models.CharField(help_text='رقم واتساب أو رمز جهاز FCM', max_length=120)),
                ('body', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', 'في الطابور'), ('sent', 'أُرسلت'), ('delivered', 'وصلت'), ('read', 'قُرئت'), ('failed', 'فشلت')], db_index=True, default='queued', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='withdrawals.withdrawalrequest')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.messagetemplate')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_ref', models.CharField(max_length=120)),
                ('reply_payload', models.JSONField(blank=True, default=dict)),
                ('button_id', models.CharField(blank=True, help_text='مثل received / not_received', max_length=60)),
                ('text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message')),
            ],
            options={
                'db_table': 'message_replies',
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('provider_message_id',), name='uniq_reply_provider_id')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['request', 'created_at'], name='messages_request_d0e191_idx'),
        ),
    ]
