# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('creator', 'مبدع'), ('admin', 'إدارة'), ('system', 'النظام'), ('owner', 'صاحب حساب استلام')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('entity', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity', 'entity_id', 'created_at'], name='audit_log_entity_2b8056_idx')],
            },
        ),
    ]
