# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('type', models.CharField(choices=[('receiving', 'حساب استلام مصري'), ('creator_balance', 'رصيد مبدع'), ('fees', 'رسوم'), ('cash', 'صندوق/سيولة')], db_index=True, max_length=20)),
                ('ref_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], default='EGP', max_length=3)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ledger_accounts',
                'constraints': [models.UniqueConstraint(fields=('type', 'ref_id', 'currency'), name='uniq_ledger_account_per_ref')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_id', models.UUIDField(db_index=True)),
                ('debit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], max_length=3)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgeraccount')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['account', 'created_at'], name='ledger_entr_account_14b5c0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ledger_amounts_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ledger_entry_single_side')],
            },
        ),
    ]
