# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.withdrawals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.withdrawals.models.generate_code, editable=False, max_length=12, unique=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('amount_egp', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('fee_egp', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('net_amount_egp', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], default='EGP', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'بدأ الطلب'), ('tiktok_processing', 'TikTok يعالج'), ('tiktok_sent', 'TikTok أرسل'), ('tiktok_rejected', 'TikTok رفض'), ('received_eg', 'وصل للحساب المصري'), ('approved', 'معتمد للدفع'), ('paid', 'مدفوع'), ('not_received', 'لم يصل'), ('cancelled', 'ملغى')], db_index=True, default='initiated', max_length=20)),
                ('tiktok_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('initiated_at', models.DateTimeField()),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('ledger_txn_id', models.UUIDField(blank=True, help_text='قيد الإيداع عند received_eg', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='creators.creator')),
                ('receiving_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='receiving.receivingaccount')),
            ],
            options={
                'verbose_name': 'طلب سحب',
                'verbose_name_plural': 'طلبات السحب',
                'db_table': 'withdrawal_requests',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('notification', 'إشعار TikTok'), ('email', 'بريد TikTok'), ('owner_wa', 'رد صاحب الحساب على واتساب'), ('sms', 'رسالة بنك'), ('manual', 'إدخال إدارة')], db_index=True, max_length=20)),
                ('kind', models.CharField(choices=[('processing', 'قيد المعالجة'), ('sent', 'تم الإرسال'), ('rejected', 'مرفوض'), ('received', 'وصل')], max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('parsed_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('parsed_currency', models.CharField(blank=True, max_length=3)),
                ('parsed_txn_id', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('package_sig_ok', models.BooleanField(default=False)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_signals', to='creators.creator')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='withdrawals.withdrawalrequest')),
            ],
            options={
                'db_table': 'withdrawal_signals',
            },
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'initiated_at'], name='withdrawal__status_d8931d_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['creator', 'initiated_at'], name='withdrawal__creator_78a5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['receiving_account', 'sent_at'], name='withdrawal__receivi_bd8e29_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('tiktok_txn_id__isnull', False)), fields=('tiktok_txn_id',), name='uniq_withdrawal_tiktok_txn'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'initiated')), fields=('creator',), name='uniq_open_initiated_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('fee_egp__gte', 0), ('net_amount_egp__gte', 0)), name='withdrawal_amounts_non_negative'),
        ),
        migrations.AddIndex(
            model_name='withdrawalsignal',
            index=models.Index(fields=['request', 'created_at'], name='withdrawal__request_82c80d_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalsignal',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uniq_signal_dedupe_key'),
        ),
    ]
