# Generated by Django 5.2.17 on 2026-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='stale_prompt_sent_at',
            field=models.DateTimeField(blank=True, help_text='وقت سؤال المبدع بعد مضي المهلة بلا إشارة', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalsignal',
            name='kind',
            field=models.CharField(choices=[('processing', 'قيد المعالجة'), ('sent', 'تم الإرسال'), ('rejected', 'مرفوض'), ('received', 'وصل'), ('not_completed', 'أفاد المبدع بعدم إتمام السحب')], max_length=20),
        ),
    ]
