# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok')], default='tiktok', max_length=20)),
                ('open_id', models.CharField(max_length=128, unique=True)),
                ('union_id', models.CharField(blank=True, max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('follower_count', models.BigIntegerField(default=0)),
                ('access_token_enc', apps.common.fields.EncryptedTextField(blank=True, default='')),
                ('refresh_token_enc', apps.common.fields.EncryptedTextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('token_expired', 'انتهى التوكن'), ('revoked', 'أُلغي الربط')], default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_accounts', to='creators.creator')),
            ],
            options={
                'db_table': 'creator_platform_accounts',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=40)),
                ('outcome', models.CharField(choices=[('success', 'نجحت'), ('failed', 'فشلت')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.creatorplatformaccount')),
            ],
            options={
                'db_table': 'sync_logs',
            },
        ),
        migrations.AddConstraint(
            model_name='creatorplatformaccount',
            constraint=models.UniqueConstraint(fields=('creator', 'platform'), name='uniq_platform_account_per_creator'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['account', 'created_at'], name='sync_logs_account_68cbed_idx'),
        ),
    ]
