# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receiving', '0001_initial'),
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_egp', models.DecimalField(decimal_places=4, max_digits=18)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('bank_ref', models.CharField(blank=True, max_length=120)),
                ('sender_hint', models.CharField(blank=True, help_text='ما يظهر عن المرسِل إن وُجد', max_length=200)),
                ('source', models.CharField(choices=[('sms', 'رسالة بنك'), ('notification', 'إشعار تطبيق البنك'), ('statement', 'كشف حساب'), ('manual', 'إدخال إدارة')], max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='withdrawals.withdrawalrequest')),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='receiving.receivingaccount')),
            ],
            options={
                'db_table': 'incoming_transfers',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('unique_address', 'عنوان استلام خاص'), ('account_amount_time', 'الحساب والمبلغ والزمن'), ('owner_reply', 'رد صاحب الحساب'), ('creator_reply', 'رد المبدع'), ('admin', 'قرار إدارة')], max_length=30)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('decided_by', models.CharField(choices=[('auto', 'آلي'), ('owner', 'صاحب الحساب'), ('admin', 'إدارة')], max_length=10)),
                ('decided_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='withdrawals.withdrawalrequest')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='reconciliation.incomingtransfer')),
            ],
            options={
                'db_table': 'reconciliation_matches',
            },
        ),
        migrations.AddIndex(
            model_name='incomingtransfer',
            index=models.Index(fields=['receiving_account', 'received_at'], name='incoming_tr_receivi_ffe6e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount_egp__gt', 0)), name='incoming_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uniq_incoming_transfer_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_request__isnull', False)), fields=('matched_request',), name='uniq_transfer_per_request'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatch',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='match_confidence_range'),
        ),
    ]
