# Generated by Django 5.2.17 on 2026-08-30 10:14

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('collector_id', models.CharField(max_length=64, unique=True)),
                ('secret_enc', apps.common.fields.EncryptedTextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'جهاز جامع',
                'verbose_name_plural': 'أجهزة الجامع',
                'db_table': 'collector_devices',
            },
        ),
        migrations.AddField(
            model_name='incomingtransfer',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'بلا مطابقة'), ('matched', 'مطابَق'), ('ambiguous', 'أكثر من مرشح'), ('ignored', 'مُستبعَد')], db_index=True, default='unmatched', max_length=12),
        ),
        migrations.AddField(
            model_name='incomingtransfer',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='reconciliation.collectordevice'),
        ),
    ]
