# Generated by Django 5.2.17 on 2026-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_collectordevice_incomingtransfer_match_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='decided_by',
            field=models.CharField(choices=[('auto', 'آلي'), ('owner', 'صاحب الحساب'), ('creator', 'المبدع'), ('admin', 'إدارة')], max_length=10),
        ),
    ]
