# Generated by Django 5.2.17 on 2026-08-29 14:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('withdrawals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(default='manual', max_length=40)),
                ('currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], default='EGP', max_length=3)),
                ('enabled', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'payout_methods',
            },
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري')], default='EGP', max_length=3)),
                ('destination', models.CharField(blank=True, help_text='وسيلة استلام المبدع', max_length=150)),
                ('reference', models.CharField(blank=True, help_text='مرجع التحويل المُسجَّل يدويًا', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'بانتظار التنفيذ'), ('executed', 'نُفِّذ'), ('failed', 'فشل')], db_index=True, default='pending', max_length=10)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('ledger_txn_id', models.UUIDField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_payouts', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payouts.payoutmethod')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='withdrawals.withdrawalrequest')),
            ],
            options={
                'db_table': 'payout_transactions',
                'constraints': [models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0), ('net_amount__gt', 0), ('fee_amount__gte', 0)), name='payout_amounts_valid'), models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('reference',), name='uniq_payout_reference')],
            },
        ),
    ]
